---
- hosts: 
    - swarm_manager
    - swarm_worker
  gather_facts: True
  roles:
    - integr8.ansible_role_docker_swarm
    - integr8.ansible_role_traefik
    - integr8.ansible_role_sonatype_nexus
    - integr8.ansible_role_sonarqube